# Generated by Django 3.2.11 on 2022-01-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('date_publish', models.DateField()),
                ('ISBN_number', models.IntegerField()),
                ('counts_page', models.IntegerField()),
                ('link_poster', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
