# Generated by Django 3.2.11 on 2022-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_book_isbn_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=100)),
                ('intitle', models.CharField(max_length=100)),
                ('inautor', models.CharField(max_length=100)),
                ('inpublisher', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('lccn', models.CharField(max_length=100)),
                ('oclc', models.CharField(max_length=100)),
            ],
        ),
    ]
